### ISSUE TITLE
Errors with check_env.py

### ISSUE THREAD

**Issue by jbosch-noaa** [jonathanrocher/pandas_tutorial#25]
Hey there! I am trying to make sure I have everything installed before the workshop next week and ran in to some errors when running check_eny.py. I cloned the repo but it seems I am missing   "sea_levels" and "Obtaining Tide Gauge Data.html".   See below:

jennifer.bosch@IOOS-L-1736542  ~/Documents/GitHub/pandas_tutorial (master)
$ python check_env.py
# .....E.
## ERROR: **main**.test_read_html

Traceback (most recent call last):
  File "C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "check_env.py", line 39, in test_read_html
    "sea_levels", "Obtaining Tide Gauge Data.html"))
  File "C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\lib\site-packages\pandas\io\html.py", line 874, in read_html
    parse_dates, tupleize_cols, thousands, attrs, encoding)
  File "C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\lib\site-packages\pandas\io\html.py", line 736, in _parse
    raise_with_traceback(retained)
  File "C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\lib\site-packages\pandas\io\html.py", line 730, in _parse
    tables = p.parse_tables()
  File "C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\lib\site-packages\pandas\io\html.py", line 196, in parse_tables
    tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
  File "C:\Users\jennifer.bosch\AppData\Local\Continuum\Miniconda2\lib\site-packages\pandas\io\html.py", line 426, in _parse_tables
    raise ValueError('No tables found')
ValueError: No tables found

---

Ran 7 tests in 14.345s

FAILED (errors=1)

**Comment by bondarevts** [comment]
It's because there is no directory named "demos". As temporary solution I removed argument "demos" from join command inside `test_read_html` function and then run check.

**Comment by jonathanrocher** [comment]
Sorry about that! Thanks @bondarevts for finding a workaround. I am pushing a PR to fix this...
